### ISSUE TITLE
Not working. 

### ISSUE THREAD

**Issue by gladsonrobinson** [mobinni/material-date-picker#10]
Its not showing um anything,

**Comment by mobinni** [comment]
I can't help you with that short an explanation, can you please tell me the steps you went through

**Comment by gladsonrobinson** [comment]
This is my Index page..
```
<!doctype html>
<html lang="en"  ng-app="myApp">
<head>
  <meta charset="utf-8">
  <title></title>

  <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/angular_material/0.7.0/angular-material.min.css">

  <link rel="stylesheet" href="bower_components/material-date-picker/build/styles/mbdatepicker.css">

<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js"></script>



    <script src="//ajax.googleapis.com/ajax/libs/angular_material/0.8.2/angular-material.min.js"></script>
   
    <script src="bower_components/material-date-picker/build/mbdatepicker.js"></script>

  <script src="app.js"></script>

</head>
<body ng-controller="MyCtrl">

<mb-datepicker element-id='date1'
               date-message=""
               text-color="#EFEF23"
               line-color="#DDFE66"
               date="date"
               date-format="YYYY-MM-DD"></mb-datepicker>

</body>
</html>
```
This is my app.js page.. 

```
var myApp = angular.module('myApp',[]);

myApp.controller('MyCtrl',['$scope',function ($scope) {
  

}]);
```

Is am missing any thing. 

Thanks for your response

**Comment by mobinni** [comment]
var myApp = angular.module('myApp',['materialDatePicker']);

**Comment by gladsonrobinson** [comment]
Thanks.. 
I can see a text box. 
Now am getting some error. 

```
ReferenceError: moment is not defined
    at link (http://localhost/Angular/datepicker/bower_components/material-date-picker/build/mbdatepicker.js:57:19)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:70:93
    at Z (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:70:149)
    at A (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:59:203)
    at g (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:51:299)
    at A (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:59:147)
    at g (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:51:299)
    at g (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:51:316)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:50:415
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:18:8 <mb-datepicker element-id="date1" date-message="" text-color="#EFEF23" line-color="#DDFE66" date="date" date-format="YYYY-MM-DD" class="ng-isolate-scope">angular.js:11607 (anonymous function)angular.js:8557 $getangular.js:8221 Zangular.js:7729 Aangular.js:7078 gangular.js:7724 Aangular.js:7078 gangular.js:7081 gangular.js:6957 (anonymous function)angular.js:1450 (anonymous function)angular.js:14401 $get.l.$evalangular.js:14500 $get.l.$applyangular.js:1448 (anonymous function)angular.js:4185 eangular.js:1446 dangular.js:1466 tcangular.js:1360 Jdangular.js:26176 (anonymous function)angular.js:2744 aangular.js:3014 c
index.html:1 GET http://localhost/Angular/datepicker/images/white_arrow_right.svg 404 (Not Found)
```

**Comment by mobinni** [comment]
You also need to reference momentjs, you can bower install this if need be or cdn it

**Comment by gladsonrobinson** [comment]
Thanks again.. 

error: 
```
TypeError: undefined is not a function
    at db (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:25:511)
    at s.css (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:165:409)
    at Object.Q.(anonymous function) [as css] (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:167:424)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:235:23
    at Object.fn (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:122:53)
    at l.$get.l.$digest (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:123:138)
    at l.$get.l.$apply (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:126:58)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:17:479
    at Object.e [as invoke] (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:36:315)
    at d (https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:17:400)
index.html:1 GET http://localhost/Angular/datepicker/images/white_arrow_left.svg 404 (Not Found)
index.html:1 GET http://localhost/Angular/datepicker/images/white_arrow_right.svg 404 (Not Found)
index.html:1 GET http://localhost/Angular/datepicker/images/grey_arrow_left.svg 404 (Not Found)
index.html:1 GET http://localhost/Angular/datepicker/images/grey_arrow_right.svg 404 (Not Found)

```

**Comment by mobinni** [comment]
well you don't have the arrow files, you can find them in the repo and put them in your images folder, the picker should be working tho, the error you can ignore, it's a generic jquery error

**Comment by gladsonrobinson** [comment]
I cant find any images in repo..

**Comment by gladsonrobinson** [comment]
How can I get the images

**Comment by mobinni** [comment]
I must have removed them from the repo, my bad :p http://iconmonstr.com/?s=arrow pick the arrows you see fit and name them like they are named in the error

**Comment by ricardotechnogi** [comment]
do I need jquery for this?

**Comment by mobinni** [comment]
no
