### ISSUE TITLE
Broken dependency on Moment

### ISSUE THREAD

**Issue by csvan** [mobinni/material-date-picker#32]
Currently, installing via npm and trying to use the module yields:

```
ReferenceError: moment is not defined
    at link (http://localhost:3001/node_modules/material-date-picker/build/mbdatepicker.js:54:19)
    at http://localhost:3001/node_modules/angular/angular.js:8598:44
    at invokeLinkFn (http://localhost:3001/node_modules/angular/angular.js:8604:9)
    at nodeLinkFn (http://localhost:3001/node_modules/angular/angular.js:8113:11)
    at compositeLinkFn (http://localhost:3001/node_modules/angular/angular.js:7514:13)
    at compositeLinkFn (http://localhost:3001/node_modules/angular/angular.js:7518:13)
    at compositeLinkFn (http://localhost:3001/node_modules/angular/angular.js:7518:13)
    at publicLinkFn (http://localhost:3001/node_modules/angular/angular.js:7388:30)
    at compile (http://localhost:3001/node_modules/angular-ui-router/release/angular-ui-router.js:4026:9)
    at invokeLinkFn (http://localhost:3001/node_modules/angular/angular.js:8604:9) <mb-datepicker element-id="date1" input-class="testClass" input-name="testName" arrows="arrows" calendar-header="header" date="date" date-format="YYYY-MM-DD" class="ng-isolate-scope">
```

Installing and including Moment manually resolves the issue.

**Comment by mobinni** [comment]
bower install moment

**Comment by csvan** [comment]
When you install via NPM this does not happen.

**Comment by csvan** [comment]
This does not happen when installing via NPM (your package.json does not list Moment as a dep).
